version: '3.8'

services:
  # Our Own Mail Server (100% FREE)
  mail-server:
    image: catatnight/postfix
    container_name: openpolicy_mail_server
    hostname: mail.openpolicy.me
    ports:
      - "25:25"    # SMTP
      - "587:587"  # SMTP with TLS
      - "993:993"  # IMAP with SSL
    environment:
      - maildomain=openpolicy.me
      - smtp_user=openpolicy:openpolicy123
      - smtp_pass=openpolicy123
    volumes:
      - mail_data:/var/mail
      - mail_logs:/var/log
      - ./mail_config:/etc/postfix
    restart: unless-stopped
    networks:
      - mail_network

  # Spam Filtering (FREE)
  spamassassin:
    image: pschiffe/spamassassin
    container_name: openpolicy_spam_filter
    ports:
      - "783:783"
    volumes:
      - spam_data:/var/lib/spamassassin
    restart: unless-stopped
    networks:
      - mail_network

  # Virus Scanning (FREE)
  clamav:
    image: clamav/clamav:latest
    container_name: openpolicy_virus_scanner
    volumes:
      - clamav_data:/var/lib/clamav
    restart: unless-stopped
    networks:
      - mail_network

  # Webmail Interface (FREE)
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: openpolicy_webmail
    ports:
      - "8082:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=postgres
      - ROUNDCUBEMAIL_DB_HOST=db
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube123
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.openpolicy.me
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mail_network

  # Database for Roundcube
  db:
    image: postgres:15
    container_name: openpolicy_mail_db
    environment:
      POSTGRES_DB: roundcube
      POSTGRES_USER: roundcube
      POSTGRES_PASSWORD: roundcube123
    volumes:
      - mail_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mail_network

volumes:
  mail_data:
  mail_logs:
  spam_data:
  clamav_data:
  mail_db_data:

networks:
  mail_network:
    driver: bridge
